### PR TITLE
Allow default to be a coderef or object overloading &{}

### PR DESCRIPTION
**Pull request by tobyink**
This allows for `$flag->default(sub { ... })` or for the default to be an object overloading `&{}`.

Issue #43

### CODE REVIEW

**Comment by tobyink** [comment]
Oh wow, 100% score on codecov first try!

🥳

**Review by sago35 — APPROVED** [review]
Excellent PR.
LGTM

**Comment by sago35** [comment]
Thanks for your excellent contribution!
now marging.

**Comment by tobyink** [comment]
No problem.

I would appreciate a release on CPAN including these changes soon, if you have the time.

**Comment by sago35** [comment]
@tobyink Released :+1: 
https://metacpan.org/release/TAKASAGO/Getopt-Kingpin-0.10

**Comment by tobyink** [comment]
Thanks

**Pull request merged**
